# 오류 코드보다는 예외를 사용
``` java
// 안좋은 예
// 호출자 코드가 복잡해진다 (호출한 즉시 오류를 확인해야 하기 때문)
public class DeviceController {
  ...
  ...
  public void sendShutDown() {
    DeviceHandle handle = getHandle(DEV1);
    if (handle != DeviceHandle.INVALID) {
      retrieveDeviceRecord(handle);
      
      if (record.getStatus() != DEVICE_SUSPENDED) {
        pauseDevice(handle);
        clearDeviceWorkQueue(handle);
        closeDevice(handle);
      } else {
        logger.log("Device suspended. Unable to shut down");
      }
    } else {
      logger.log("Invalid handle for: " + DEV1.toString());
    }
  }
  ...
  ...
  ...
}
```

``` java
// 좋은 예
public class DeviceController {
  ...
  ...
  public void sendShutDown() {
    try {
      tryToShutDown();
    } catch (DeviceShutDownError e) {
      logger.log(e);
    }
  }
    
  private void tryToShutDown() throws DeviceShutDownError {
    DeviceHandle handle = getHandle(DEV1);
    DeviceRecord record = retrieveDeviceRecord(handle);
    pauseDevice(handle); 
    clearDeviceWorkQueue(handle); 
    closeDevice(handle);
  }
  
  private DeviceHandle getHandle(DeviceID id) {
    ...
    throw new DeviceShutDownError("Invalid handle for: " + id.toString());
    ...
  }
  ...
  ...
}
```

<br>

# try-catch-finally문을 먼저 작성
- try 블록은 트랜잭션과 비슷하다
- try 안에서 무슨 일이 생기든지 catch 블록은 프로그램을 일관성있게 유지해야 한다
- try 블록에서 무슨 일이 생기든지 호출자가 기대하는 상태를 정의하기 쉬워진다
``` java
// ex) 파일이 없으며 예외를 던지는 단위 테스트
// 이 코드는 예외를 던지지 않으므로 실패하는 단위 테스트
  @Test(expected = StorageException.class)
  public void retrieveSectionShouldThrowOnInvalidFileName() {
    sectionStore.retrieveSection("invalid - file");
  }
  
  public List<RecordedGrip> retrieveSection(String sectionName) {
    return new ArrayList<RecordedGrip>();
  }
```

``` java
// 다음은 잘못된 파일을 접근하게 구현한 코드 (예외를 던짐)
// 이 시점에서 catch 블록에서 예외 유형을 좁혀 리팩토링
  public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
      FileInputStream stream = new FileInputStream(sectionName)
    } catch (Exception e) {
      throw new StorageException("retrieval error", e);
    }
  return new ArrayList<RecordedGrip>();
  }
```

``` java
  public List<RecordedGrip> retrieveSection(String sectionName) {
    try {
      FileInputStream stream = new FileInputStream(sectionName);
      stream.close();
    } catch (FileNotFoundException e) {
      throw new StorageException("retrieval error", e);
    }
    return new ArrayList<RecordedGrip>();
  }
```

<br>

# 미확인 예외를 사용
- 확인된 예외는 OCP를 위반한다 (하위 단계에서 코드를 변경하면 상위 단계 메서드를 전부 변경해야 한다)

<br>

# 예외에 의미를 제공
- 예외를 던질때는 전후 상황을 충분히 덧붙인다. 그러면 오류가 발생한 원인과 위치를 찾기가 쉬워진다
- 오류 메시지에 정보를 담아 예외와 함께 던진다

<br>

# 호출자를 고려해 예외 클래스를 정의
``` java
// 허접한 예외 처리
  ACMEPort port = new ACMEPort(12);
  try {
    port.open();
  } catch (DeviceResponseException e) {
    reportPortError(e);
    logger.log("Device response exception", e);
  } catch (ATM1212UnlockedException e) {
    reportPortError(e);
    logger.log("Unlock exception", e);
  } catch (GMXError e) {
    reportPortError(e);
    logger.log("Device response exception");
  } finally {
    ...
    ...
    ...
  }
```

``` java
// 호출하는 라이브러리 api를 감싸면서 예외 유형 하나를 반환
// 외부 api를 감싸면 의존성이 크게 줄어든다 (테스트 하기도 쉬워짐)
  LocalPort port = new LocalPort(12);
  try {
    port.open();
  } catch (PortDeviceFailure e) {
    reportError(e);
    logger.log(e.getMessage(), e);
  } finally {
    ...
    ...
  }
  
  public class LocalPort {
    private ACMEPort innerPort;
    public LocalPort(int portNumber) {
      innerPort = new ACMEPort(portNumber);
    }
    
    public void open() {
      try {
        innerPort.open();
      } catch (DeviceResponseException e) {
        throw new PortDeviceFailure(e);
      } catch (ATM1212UnlockedException e) {
        throw new PortDeviceFailure(e);
      } catch (GMXError e) {
        throw new PortDeviceFailure(e);
      }
  }
    ...
    ...
  }
```

<br>

# 정상 흐름을 정의
``` java
// 비용 청구 애플리케이션에서 총계를 계산하는 허접한 코드
// 식비를 비용으로 청구했다면 직원이 청구한 식비를 총계에 더한다
// 식비를 비용으로 청구하지 않았다면 일일 기본 식비를 총계에 더한다
  try {
    MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
    m_total += expenses.getTotal();
  } catch(MealExpensesNotFound e) {
    m_total += getMealPerDiem();
  }
```

``` java
// 특수 상황을 처리할 필요가 없게 만들면 더 좋다
  MealExpenses expenses = expenseReportDAO.getMeals(employee.getID());
  m_total += expenses.getTotal();
  
  public class PerDiemMealExpenses implements MealExpenses {
    public int getTotal() {
      // 기본값으로 일일 기본 식비를 반환
    }
  }
```

<br>

# null을 반환하지 마라
``` java
// 안좋은 예
// 호출자에게 문제를 떠넘긴다
  public void registerItem(Item item) {
    if (item != null) {
      ItemRegistry registry = peristentStore.getItemRegistry();
      if (registry != null) {
        Item existing = registry.getItem(item.getID());
        if (existing.getBillingPeriod().hasRetailOwner()) {
          existing.register(item);
        }
      }
    }
  }
```

``` java
// 안좋은 예
  List<Employee> employees = getEmployees();
  if (employees != null) {
    for(Employee e : employees) {
      totalPay += e.getPay();
    }
  }
```

``` java
// 좋은 예
// getEmployees를 변경해 빈 리스트를 반환
  List<Employee> employees = getEmployees();
  for(Employee e : employees) {
    totalPay += e.getPay();
  }
  
  public List<Employee> getEmployees() {
    if( .. there are no employees .. )
      return Collections.emptyList();
    }
  }
```

<br>

# null을 전달하지 마라
``` java
// 안좋은 예
// 누군가 인수로 null을 전달한다면 오류 발생
public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    return (p2.x – p1.x) * 1.5;
  }
  ...
}
```

``` java
// 안좋은 예
// NullPointerException은 발생하지 않지만 InvalidArgumentException을 잡아내는 처리기가 필요
public class MetricsCalculator {
  public double xProjection(Point p1, Point p2) {
    if(p1 == null || p2 == null){
      throw InvalidArgumentException("Invalid argument for MetricsCalculator.xProjection");
    }
    return (p2.x – p1.x) * 1.5;
  }
}
```




















